# premii Nobel pentru fizica sau chimie conferite cercetatoarelor;
# numele persoanelor sunt convertite in litere mari via ucase();
# denumirea premiului e in limba suedeza ('sv')

# detalii la <https://www.nobelprize.org/about/linked-data-examples/>

PREFIX nobel: <http://data.nobelprize.org/terms/>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX foaf: <http://xmlns.com/foaf/0.1/>

SELECT DISTINCT (ucase(?name) AS ?cname) ?prizeName ?category WHERE {
  ?person rdf:type nobel:Laureate ;
    rdfs:label ?name ; foaf:gender ?gender ;
    nobel:nobelPrize ?prize .
  ?prize rdfs:label ?prizeName ; nobel:category ?category .
FILTER (lang(?prizeName) = 'sv' && ?gender = 'female' &&
    (?category = nobel:Chemistry || ?category = nobel:Physics))
} ORDER BY desc(?cname)
LIMIT 7 
